name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello World! GitHub Actions is working!"
